### ISSUE TITLE
Stilmulsoft 2018.3.3 Update Issue with System Variable time

### ISSUE THREAD

**Issue by eDatabz** [stimulsoft/Samples-JS-PHP#1]
Good Day, 
kindly note after updating stimulsoft.report.js, stimulsoft.viewer.js to2018.3.3 
there is an issue displaying System Variable time on JS-PHP platform.

![30](https://user-images.githubusercontent.com/44502833/47573129-ccd88b80-d8f9-11e8-9ca0-58d1c1894904.PNG)
![31](https://user-images.githubusercontent.com/44502833/47573138-d3670300-d8f9-11e8-9e3d-f4bafe169fee.PNG)

**Comment by HighAley** [comment]
This is an issue of the Stimulsoft Reports product. It could not be solved using the code of these samples.
Please, contact the Stimulsoft support service.

**Comment by VladimirHot** [comment]
I close this issue, if it repeats - please create a new ticket or contact support.
