### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by MildSYang** [stimulsoft/Samples-JS-PHP#2]
export excel.
If the column is a numeric type, It's ok.
but if the column is a String or other , It`s show "NaN"
![image](https://user-images.githubusercontent.com/11704527/53146942-f3c17880-35e0-11e9-9682-f4eec8200695.png)
![image](https://user-images.githubusercontent.com/11704527/53146973-0d62c000-35e1-11e9-99f5-30bbde12a560.png)

i use "WPS"

**Comment by HighAley** [comment]
Do you get the issue with one of the samples?

**Comment by VladimirHot** [comment]
I close this issue, if it repeats - please create a new ticket or contact support.
