### ISSUE TITLE
stimulsoft viewer fullscreen only fits the container

### ISSUE THREAD

**Issue by amin125** [stimulsoft/Samples-JS-PHP#3]
I have a report (using stimulsoft viewer) inside a small container that when i want to show in full screen, it only fits the container. I want the viewer to ignore the browser and go a real full screen. Is that possible ? (not even the browser toolbars are shown)

scope.init = function () 
{
                    var options = new Stimulsoft.Viewer.StiViewerOptions;
                    options.toolbar.zoom = Stimulsoft.Viewer.StiZoomMode.PageWidth;
                    options.appearance.showTooltipsHelp = false;
                    options.appearance.openLinksTarget = "_blank";
                    options.appearance.scrollbarsMode = true;
                    options.appearance.fullScreenMode = true;

                    scope.viewer = new $window.Stimulsoft.Viewer.StiViewer(options, 'StiViewer', false);
}

**Comment by VladimirBLR** [comment]
Hello,

You can use JavaScript method:

```
function GoInFullscreen(element) {
	if(element.requestFullscreen)
		element.requestFullscreen();
	else if(element.mozRequestFullScreen)
		element.mozRequestFullScreen();
	else if(element.webkitRequestFullscreen)
		element.webkitRequestFullscreen();
	else if(element.msRequestFullscreen)
		element.msRequestFullscreen();
}
```

**element** - this is a document or viewer DOM element.

Thank you.

**Comment by amin125** [comment]
@VladimirBLR should this be applied when clicking the fullscreen event of the stimusoft viewer ?

**Comment by VladimirBLR** [comment]
It is not possible to automatically switch to real full-screen mode, it is prohibited by the security policy of the browser. You need to put any button on the page and add a click event in which the specified function will be called.

Thank you.

**Comment by amin125** [comment]
@VladimirBLR  thank you that was very helpful ! But how can I add scroll option only on full screen ?
options.appearance.scrollbarsMode = true;

**Comment by amin125** [comment]
@VladimirBLR Is there any other way than using 2 fullscreen buttons to make it work ?

**Comment by VladimirBLR** [comment]
Please try to use this code:

```
<script>
    function GoInFullscreen(element) {
        if (element.requestFullscreen)
            element.requestFullscreen();
        else if (element.mozRequestFullScreen)
            element.mozRequestFullScreen();
        else if (element.webkitRequestFullscreen)
            element.webkitRequestFullscreen();
        else if (element.msRequestFullscreen)
            element.msRequestFullscreen();
    }

    jsStiWebViewer1._changeFullScreenMode = jsStiWebViewer1.changeFullScreenMode;
    jsStiWebViewer1.changeFullScreenMode = function (value) {
        jsStiWebViewer1._changeFullScreenMode(value);

        if (value) GoInFullscreen(jsStiWebViewer1.controls.viewer);
    }
</script>
```

**jsStiWebViewer1** - 'js' + component ID
